Refactor help implementation for commands
- Implement standalone help messages for each command
- Add detailed, standardized help messages
- Update tests to match new help message format

Part of #21

diff --git a/bin/cat-which b/bin/cat-which
--- a/bin/cat-which
+++ b/bin/cat-which
@@ -15,15 +15,37 @@
 # Not a plain text: /bin/zsh
 # ```
 
-if [[ $1 == '' ]] ; then
-  echo 'Error: 1 or more arguments required' > /dev/stderr
-  exit 1
-fi
+function show_help () {
+  cat << 'EOF'
+cat-which - Display contents of executable files in PATH
+
+Usage:
+  cat-which COMMAND
+  cat-which --help
+
+Arguments:
+  COMMAND            Name of the command to display
+
+Options:
+  --help            Show this help message
+
+Notes:
+  - Uses bat/batcat if available, falls back to cat
+  - Binary files will be skipped with an error message
+EOF
+}
+
+[[ $1 == --help ]] && show_help && exit 0
 
 dir=$(dirname "$0")
 
 # shellcheck disable=SC1091
 source "$dir/../define-options.sh"
+
+if [[ $1 == '' ]] ; then
+  echo 'Error: 1 or more arguments required' > /dev/stderr
+  exit 1
+fi
 
 if command -v batcat > /dev/null 2>&1 || command -v bat > /dev/null 2>&1 ; then
   cat="batcat $BASH_TOYS_BATCAT_OPTIONS"
@@ -39,25 +61,3 @@ else
   echo "Not a plain text: $cmd_path" > /dev/stderr
   exit 1
 fi
-
-# The MIT License (MIT)
-#
-# Copyright (c) 2025- aiya000
-#
-# Permission is hereby granted, free of charge, to any person obtaining a copy
-# of this software and associated documentation files (the "Software"), to deal
-# in the Software without restriction, including without limitation the rights
-# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-# copies of the Software, and to permit persons to whom the Software is
-# furnished to do so, subject to the following conditions:
-#
-# The above copyright notice and this permission notice shall be included in
-# all copies or substantial portions of the Software.
-#
-# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
-# THE SOFTWARE.
diff --git a/bin/date-diff-seconds b/bin/date-diff-seconds
--- a/bin/date-diff-seconds
+++ b/bin/date-diff-seconds
@@ -8,12 +8,32 @@
 # $ date-diff-seconds '08-05 21:47' '08-05 22:33'
 # $ date-diff-seconds 21:47 22:33  -- Infer both times is today's
 
+function show_help () {
+  cat << 'EOF'
+date-diff-seconds - Calculate time difference in minutes
+
+Usage:
+  date-diff-seconds TIME1 TIME2
+  date-diff-seconds --help
+
+Arguments:
+  TIME1, TIME2      Time in format 'MM-DD HH:MM' or just 'HH:MM'
+                    When only HH:MM is given, current date is assumed
+
+Options:
+  --help           Show this help message
+
+Examples:
+  date-diff-seconds '08-05 21:47' '08-05 22:33'   # Specific dates
+  date-diff-seconds 21:47 22:33                    # Times today
+EOF
+}
+
+[[ $1 == --help ]] && show_help && exit 0
+
 if [[ $# -lt 2 ]] ; then
-  {
-    echo "help:"
-    declare -f "$0" | head
-  } > /dev/stderr
-  return 1
+  echo "Error: TIME1 and TIME2 arguments are required" >&2
+  exit 1
 fi
 
 this_year=$(date +%Y)
@@ -37,26 +57,4 @@ now=$(get_fully_qualified_date "$1")
 from_raw=$(date --date "$from" +%s)
 now_raw=$(date --date "$now" +%s)
 
-echo "$(( (from_raw - now_raw) / 60))"
-
-# The MIT License (MIT)
-#
-# Copyright (c) 2025- aiya000
-#
-# Permission is hereby granted, free of charge, to any person obtaining a copy
-# of this software and associated documentation files (the "Software"), to deal
-# in the Software without restriction, including without limitation the rights
-# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-# copies of the Software, and to permit persons to whom the Software is
-# furnished to do so, subject to the following conditions:
-#
-# The above copyright notice and this permission notice shall be included in
-# all copies or substantial portions of the Software.
-#
-# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
-# THE SOFTWARE.
+echo "$(( (from_raw - now_raw) / 60 ))"
