cat-which: Reject if no arguments

diff --git a/bin/cat-which b/bin/cat-which
--- a/bin/cat-which
+++ b/bin/cat-which
@@ -15,6 +15,11 @@
 # Not a plain text: /bin/zsh
 # ```
 
+if [[ $1 == '' ]] ; then
+  echo 'Error: 1 or more arguments required' > /dev/stderr
+  exit 1
+fi
+
 dir=$(dirname "$0")
 
 # shellcheck disable=SC1091
