expects: Change `to_equal` behavior & Change the result message format

diff --git a/bin/expects b/bin/expects
--- a/bin/expects
+++ b/bin/expects
@@ -98,7 +98,7 @@ expected_value=$2
 function test_value () {
   local actual=$1 matcher=$2 expected=$3
   case $matcher in
-    to_be|to_equal)
+    to_be)
       [[ $actual -eq $expected ]]
       return $?
       ;;
@@ -108,6 +108,10 @@ function test_value () {
       ;;
     to_be_greater_than)
       [[ $actual -gt $expected ]]
+      return $?
+      ;;
+    to_equal)
+      [[ $actual == "$expected" ]]
       return $?
       ;;
     to_contain)
@@ -147,14 +151,14 @@ function format_failure_message () {
 
   # Special case for to_be_defined matcher
   if [[ $matcher == to_be_defined && -z $not ]] ; then
-    printf "FAIL: expected {actual} %s%s, but {actual} is %s" \
+    printf "FAIL: expected {actual} %s%s, but {actual} is '%s'" \
       "$not" "$matcher" "$visible_actual"
   else
     if [[ -n $expected ]] ; then
-      printf "FAIL: expected {actual} %s%s %s, but {actual} is: %s" \
+      printf "FAIL: expected {actual} %s%s '%s', but {actual} is '%s'" \
         "$not" "$matcher" "$expected" "$visible_actual"
     else
-      printf "FAIL: expected {actual} %s%s, but {actual} is: %s" \
+      printf "FAIL: expected {actual} %s%s, but {actual} is '%s'" \
         "$not" "$matcher" "$visible_actual"
     fi
   fi
